name: EN - Generate and Upload Wallpapers to Subreddit

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Mondat at 9:00 UTC
  workflow_dispatch:
jobs:
  generate-and-upload-wallpapers:
    runs-on: ubuntu-latest
    env:
      TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
      CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      SUBREDDIT: AndroidTVWallpapers
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TMDB Wallpaper Generation Script
        run: |
          python -u TMDB.py

      - name: Upload Wallpapers to Subreddit
        run: |
          python -u upload_wallpaper.py
