name: BR - Generate Wallpapers and Commit

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Mondat at 9:00 UTC
  workflow_dispatch:
jobs:
  generate-wallpapers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
      LANGUAGE: pt-BR
      LANGUAGE_SHORT: br
      NOW_TRENDING_TEXT: Em alta em
      AVAILABLE_ON_TEXT: Disponível em
      SEASON_TEXT: Temporada
      SEASONS_TEXT: Temporadas
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TMDB Wallpaper Generation Script
        run: |
          python -u TMDB.py

      - name: Commit and Push generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "tmdb_backgrounds/${LANGUAGE_SHORT}/" "wallpapers_${LANGUAGE_SHORT}.json"
          git commit -m "Auto-update: New TMDB wallpapers and wallpapers_${LANGUAGE_SHORT}.json" || echo "No changes to commit"
          git push
